package cn.com.agree.huanan.ap.al.io.service.eci.afa;

import java.util.ArrayList;
import org.springframework.stereotype.Component;

import cn.com.agree.huanan.ap.al.io.system.eci.EciChannelService;
import cn.com.agree.huanan.ap.rl.bank.base.constant.ContentEnum;
import cn.com.agree.huanan.ap.tl.communicate.content.format.ArrayNode;
import cn.com.agree.huanan.ap.tl.communicate.content.format.FieldNode;
import cn.com.agree.huanan.ap.tl.communicate.content.format.MsgBody;
import cn.com.agree.huanan.ap.tl.communicate.content.format.MsgField;
import cn.com.agree.huanan.ap.tl.communicate.content.format.MsgSegment;
import cn.com.agree.huanan.ap.tl.communicate.content.format.Node;
import cn.com.agree.huanan.ap.tl.communicate.content.format.StructNode;

/**
 * BASESVC BODF510104  试算转非实时 
 *  BODF510104 regflw
 *  综合前置
 * @author JZF
 */
@Component
public class BODF510104 extends EciChannelService {

	private static BODF510104_I i = new BODF510104_I();
	private static BODF510104_O o = new BODF510104_O();
	public BODF510104() {
		requestFormat.add(i);
		responseFormat.add(o);
	}

	public static class BODF510104_I extends MsgBody {
		private MsgSegment  msgSegment = init();
		private MsgSegment init(){
			MsgSegment messageNode = new MsgSegment();
			messageNode
			.addStructNode(new StructNode("APPBody",true,"Body")
					.addNode(new FieldNode("gsdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "gsdm", 4,0, false, "保险公司代码" )))
					.addNode(new FieldNode("ptlsh", new MsgField(ContentEnum.MessageType.STRING.toString(), "ptlsh", 30,0, false, "银行流水号" )))
					.addNode(new FieldNode("bankcode", new MsgField(ContentEnum.MessageType.STRING.toString(), "bankcode", 10,0, false, "银行总行代码" )))
					.addNode(new FieldNode("zoneno", new MsgField(ContentEnum.MessageType.STRING.toString(), "zoneno", 10,0, false, "地区代码" )))
					.addNode(new FieldNode("branch", new MsgField(ContentEnum.MessageType.STRING.toString(), "branch", 16,0, false, "银行网点代码" )))
					.addNode(new FieldNode("bxgslsh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxgslsh", 30,0, false, "保险公司的交易流水号" )))
					.addNode(new FieldNode("bxgsjydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxgsjydm", 10,0, false, "保险公司交易代码" )))
					.addNode(new FieldNode("rbjgdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "rbjgdm", 10,0, false, "人保机构代码" )))
					.addNode(new FieldNode("jyms", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyms", 10,0, false, "交易模式" )))
					.addNode(new FieldNode("jgmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "jgmc", 30,0, false, "银行出单网点名称" )))
					.addNode(new FieldNode("pzxxtbdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "pzxxtbdh", 30,0, false, "投保单号" )))
					.addNode(new FieldNode("bxxxtbrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxtbrq", 8,0, false, "投保日期" )))
					.addNode(new FieldNode("jyzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyzh", 30,0, false, "银行账户" )))
					.addNode(new FieldNode("jzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "jzh", 30,0, false, "介质号" )))
					.addNode(new FieldNode("zhmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "zhmc", 30,0, false, "账户名称" )))
					.addNode(new FieldNode("bxxxkhjl", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxkhjl", 20,0, false, "营销员号" )))
					.addNode(new FieldNode("bxxxkhjlmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxkhjlmc", 50,0, false, "营销柜员名称" )))
					.addNode(new FieldNode("acctype", new MsgField(ContentEnum.MessageType.STRING.toString(), "acctype", 1,0, true, "客户标识类型" )))
					.addNode(new FieldNode("account", new MsgField(ContentEnum.MessageType.STRING.toString(), "account", 20,0, true, "客户标识" )))
					.addNode(new FieldNode("idtype", new MsgField(ContentEnum.MessageType.STRING.toString(), "idtype", 1,0, true, "证件类型" )))
					.addNode(new FieldNode("tbrxm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrxm", 50,0, false, "投保人姓名" )))
					.addNode(new FieldNode("tbrxb", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrxb", 1,0, false, "投保人性别" )))
					.addNode(new FieldNode("tbrcsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrcsrq", 8,0, false, "投保人出生日期" )))
					.addNode(new FieldNode("tbrzjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjlx", 1,0, false, "投保人证件类别" )))
					.addNode(new FieldNode("tbrzjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjhm", 20,0, false, "投保人证件号码" )))
					.addNode(new FieldNode("tbrzjyxzq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjyxzq", 8,0, false, "投保人证件有效期" )))
					.addNode(new FieldNode("tbrzjyxq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjyxq", 8,0, false, "投保人证件有效期" )))
					.addNode(new FieldNode("tbrgj", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrgj", 5,0, false, "投保人国籍" )))
					.addNode(new FieldNode("tbrjtlxdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrjtlxdz", 50,0, false, "投保人地址" )))
					.addNode(new FieldNode("tbrdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrdz", 50,0, false, "投保人地址" )))
					.addNode(new FieldNode("tbrjtlxyb", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrjtlxyb", 6,0, false, "投保人邮编" )))
					.addNode(new FieldNode("tbryb", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbryb", 6,0, false, "投保人邮编" )))
					.addNode(new FieldNode("tbrjtlxdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrjtlxdh", 20,0, false, "投保人电话" )))
					.addNode(new FieldNode("tbrdhhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrdhhm", 20,0, false, "投保人电话号码" )))
					.addNode(new FieldNode("tbrsjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrsjhm", 11,0, false, "投保人手机号" )))
					.addNode(new FieldNode("tbremail", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbremail", 50,0, false, "投保人电子邮件" )))
					.addNode(new FieldNode("tbrssqy", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrssqy", 1,0, false, "投保人所属区域" )))
					.addNode(new FieldNode("tbrzydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzydm", 30,0, false, "投保人职业代码/工种" )))
					.addNode(new FieldNode("tbrzymc", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzymc", 30,0, false, "投保人职业名称" )))
					.addNode(new FieldNode("tbrkhlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrkhlx", 1,0, false, "投保人客户类型" )))
					.addNode(new FieldNode("tbrtbrnsr", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrtbrnsr", 15,0, false, "投保人年收入（单位：元）" )))
					.addNode(new FieldNode("tbrnsr", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrnsr", 15,0, false, "投保人年收入" )))
					.addNode(new FieldNode("tbrtbrjtnsr", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrtbrjtnsr", 15,0, false, "投保人家庭年收入（单位：元）" )))
					.addNode(new FieldNode("tbrjtnsr", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrjtnsr", 15,0, false, "投保人家庭收入" )))
					.addNode(new FieldNode("tbrybbrgx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrybbrgx", 1,0, false, "投保人、被保人关系" )))
					.addNode(new FieldNode("tbrsssx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrsssx", 5,0, false, "投保人所属市县" )))
					.addNode(new FieldNode("tbrsb", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrsb", 5,0, false, "投保人省别" )))
					.addNode(new FieldNode("bxxxsffdsyr", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxsffdsyr", 1,0, false, "是否法定受益人（YN）" )))
					.addNode(new FieldNode("tbrjmlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrjmlx", 1,0, false, "投保人居民类型" )))
					.addNode(new FieldNode("tbrdwmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrdwmc", 200,0, true, "投保人工作单位" )))
					.addNode(new FieldNode("tbrzgssjm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzgssjm", 200,0, false, "投保人个人税收居民身份" )))
					.addNode(new FieldNode("tbrwcnrsgbe", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrwcnrsgbe", 200,0, false, "投保人未成年人身故保额" )))
					.addNode(new FieldNode("tbrsg", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrsg", 15,0, false, "投保人身高" )))
					.addNode(new FieldNode("tbrtz", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrtz", 15,0, false, "投保人体重" )))
					.addNode(new FieldNode("bbrxm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrxm", 50,0, false, "被保人姓名" )))
					.addNode(new FieldNode("bxxxbbrgs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbbrgs", 50,0, false, "被保人个数" )))
					.addNode(new FieldNode("bbrbh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrbh", 50,0, false, "被保人编号" )))
					.addNode(new FieldNode("bbrxb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrxb", 1,0, false, "被保人性别" )))
					.addNode(new FieldNode("bbrsfyzj", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsfyzj", 1,0, false, "被保人是否有重疾(YN)" )))
					.addNode(new FieldNode("bbrsfcswxzy", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsfcswxzy", 1,0, false, "被保人是否从事危险职业(YN)" )))
					.addNode(new FieldNode("bbrcsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrcsrq", 8,0, false, "被保人出生日期" )))
					.addNode(new FieldNode("bbrzjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjlx", 1,0, false, "被保人证件类型" )))
					.addNode(new FieldNode("bbrzjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjhm", 20,0, false, "被保人证件号码" )))
					.addNode(new FieldNode("bbrzjyxzq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjyxzq", 8,0, false, "被保人证件有效期" )))
					.addNode(new FieldNode("bbrzjyxq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjyxq", 8,0, false, "被保人证件有效期" )))
					.addNode(new FieldNode("bbrlxdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrlxdz", 50,0, false, "被保人地址" )))
					.addNode(new FieldNode("bbrdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdz", 50,0, false, "被保人地址" )))
					.addNode(new FieldNode("bbrlxyb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrlxyb", 6,0, false, "被保人邮编" )))
					.addNode(new FieldNode("bbryb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbryb", 6,0, false, "被保人邮编" )))
					.addNode(new FieldNode("bbrlxdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrlxdh", 20,0, false, "被保人电话" )))
					.addNode(new FieldNode("bbrdhhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdhhm", 20,0, false, "被保人电话" )))
					.addNode(new FieldNode("bbrsjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsjhm", 11,0, false, "被保人手机号" )))
					.addNode(new FieldNode("bbremail", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbremail", 50,0, false, "被保人电子邮件" )))
					.addNode(new FieldNode("bbrssqy", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrssqy", 1,0, false, "被保人所属区域" )))
					.addNode(new FieldNode("bbrzydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzydm", 10,0, false, "被保人职业工种" )))
					.addNode(new FieldNode("bbrzymc", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzymc", 10,0, false, "被保人职业名称" )))
					.addNode(new FieldNode("bbrnsr", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrnsr", 15,0, false, "被保人收入" )))
					.addNode(new FieldNode("bbrgj", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrgj", 4,0, false, "被保人国籍" )))
					.addNode(new FieldNode("bbrsb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsb", 10,0, false, "被保人省别" )))
					.addNode(new FieldNode("bbrsssx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsssx", 10,0, false, "被保人所属市县" )))
					.addNode(new FieldNode("bbrxl", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrxl", 50,0, false, "被保人学历" )))
					.addNode(new FieldNode("bbrzgssjm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdwbbrzgssjmmc", 200,0, false, "被保人个人税收居民身份" )))
					.addNode(new FieldNode("bbrsg", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsg", 15,0, false, "被保人身高" )))
					.addNode(new FieldNode("bbrtz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrtz", 15,0, false, "被保人体重" )))
					.addNode(new FieldNode("bbrdwmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdwmc", 200,0, true, "被保人工作单位" )))
					.addNode(new FieldNode("syrsl", new MsgField(ContentEnum.MessageType.STRING.toString(), "syrsl", 10,0, false, "受益人数量" )))
					.addNode(new ArrayNode("syr",true,"syr_list")
							.addNode(new FieldNode("syr_syrlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_syrlx", 1,0, false, "受益人类型" )))
							.addNode(new FieldNode("syr_sysx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_sysx", 5,0, false, "受益人受益顺序" )))
							.addNode(new FieldNode("syr_xm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_xm", 50,0, false, "受益人姓名" )))
							.addNode(new FieldNode("syr_xb", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_xb", 1,0, false, "受益人性别" )))
							.addNode(new FieldNode("syr_csrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_csrq", 8,0, false, "受益人出生日期" )))
							.addNode(new FieldNode("syr_zjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_zjlx", 5,0, false, "受益人证件类型" )))
							.addNode(new FieldNode("syr_zjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_zjhm", 20,0, false, "受益人证件号码" )))
							.addNode(new FieldNode("syr_zjyxzq", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_zjyxzq", 8,0, false, "受益人证件有效期" )))
							.addNode(new FieldNode("syr_xzdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_xzdm", 20,0, false, "受益人险种代码" )))
							.addNode(new FieldNode("syr_ybbrgx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_ybbrgx", 1,0, false, "受益人、被保人关系" )))
							.addNode(new FieldNode("syr_sybl", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_sybl", 3,0, false, "受益人受益比例" )))
							.addNode(new FieldNode("syr_lxdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_lxdz", 50,0, false, "受益人地址" )))
							.addNode(new FieldNode("syr_lxdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_lxdh", 20,0, false, "受益人电话" )))
							.addNode(new FieldNode("syr_sjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_sjhm", 11,0, false, "受益人手机号码" )))
							.addNode(new FieldNode("syr_gj", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_gj", 4,0, false, "受益人国籍" )))
							.addNode(new FieldNode("syr_ssqy", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_ssqy", 1,0, false, "受益人所属区域" )))
							).addNode(new FieldNode("cpdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "cpdm", 10,0, false, "主险险种代码" )))
					.addNode(new FieldNode("zfxbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "zfxbz", 1,0, false, "主附险标志" )))
					.addNode(new FieldNode("bxxxxzgs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxxzgs", 2,0, false, "险种个数" )))
					.addNode(new ArrayNode("xz",true,"xz_list")
							.addNode(new FieldNode("bxxxcpid", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxcpid", 10,0, false, "险种编号" )))
							).addNode(new FieldNode("bxxxtbfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxtbfs", 10,0, false, "主险份数" )))
					.addNode(new FieldNode("bxxxzxbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxzxbf", 15,0, false, "主险保费" )))
					.addNode(new FieldNode("bxxxzxbe", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxzxbe", 15,0, false, "主险保额" )))
					.addNode(new FieldNode("bxxxbddsfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbddsfs", 1,0, false, "保单递送方式" )))
					.addNode(new FieldNode("bxxxsqjfxs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxsqjfxs", 1,0, false, "首期交费形式" )))
					.addNode(new FieldNode("bxxxxqjfxs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxxqjfxs", 1,0, false, "续期交费形式" )))
					.addNode(new FieldNode("bxxxjffs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxjffs", 1,0, false, "缴费方式" )))
					.addNode(new FieldNode("bxxxhllqfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxhllqfs", 10,0, false, "红利领取方式" )))
					.addNode(new FieldNode("bxxxjfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxjfnx", 10,0, false, "缴费年期" )))
					.addNode(new FieldNode("bxxxjfnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxjfnqlx", 1,0, false, "缴费年期类型" )))
					.addNode(new FieldNode("bxxxlqnq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxlqnq", 10,0, false, "领取年期" )))
					.addNode(new FieldNode("bxxxlqnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxlqnqlx", 1,0, false, "领取方式" )))
					.addNode(new FieldNode("bxxxbznqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbznqlx", 1,0, false, "保险年期类型" )))
					.addNode(new FieldNode("bxxxbznq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbznq", 10,0, false, "保险年期" )))
					.addNode(new FieldNode("bxxxkhyhzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxkhyhzh", 20,0, false, "客户银行账号" )))
					.addNode(new FieldNode("bxxxbdsddz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbdsddz", 30,0, false, "保单送达地址" )))
					.addNode(new FieldNode("bxxxsffdsyr", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxsffdsyr", 1,0, false, "是否法定受益人" )))
					.addNode(new FieldNode("bxxxjejqbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxjejqbz", 1,0, false, "自动垫交标识" )))
					.addNode(new FieldNode("bxxxrqbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxrqbz", 1,0, false, "投资日期标识" )))
					.addNode(new FieldNode("bxxxtjrbh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxtjrbh", 10,0, false, "推荐人编号" )))
					.addNode(new FieldNode("bxxxscjlqms", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxscjlqms", 10,0, false, "年金/生存金领取方式" )))
					.addNode(new FieldNode("bxxxtzzhgs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxtzzhgs", 2,0, false, "投资账户个数" )))
					.addNode(new ArrayNode("tzzh",true,"tzzh_list")
							.addNode(new FieldNode("tzzh_zhdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tzzh_zhdm", 10,0, false, "投资账户编码" )))
							.addNode(new FieldNode("tzzh_zhbl", new MsgField(ContentEnum.MessageType.STRING.toString(), "tzzh_zhbl", 6,0, false, "投资庄户比例" )))
							).addNode(new FieldNode("cplb_cpdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_cpdm", 10,0, false, "险种代码" )))
					.addNode(new FieldNode("cplb_hllqfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_hllqfs", 2,0, false, "红利领取方式" )))
					.addNode(new FieldNode("cplb_tbfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_tbfs", 10,0, false, "险种份数" )))
					.addNode(new FieldNode("cplb_jfnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jfnqlx", 2,0, false, "缴费年期类型" )))
					.addNode(new FieldNode("cplb_jfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jfnx", 4,0, false, "缴费年期" )))
					.addNode(new FieldNode("cplb_bznqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bznqlx", 2,0, false, "保障年期类型" )))
					.addNode(new FieldNode("cplb_bznq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bznq", 4,0, false, "保障年期" )))
					.addNode(new FieldNode("cplb_bxje", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxje", 15,0, false, "保额" )))
					.addNode(new FieldNode("cplb_zxbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_zxbf", 15,0, false, "保费" )))
					.addNode(new FieldNode("cplb_lqnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_lqnqlx", 4,0, false, "领取年期类型" )))
					.addNode(new FieldNode("cplb_qsnl", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_qsnl", 4,0, false, "领取起始年龄" )))
					.addNode(new FieldNode("cplb_jsnl", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jsnl", 4,0, false, "领取结束年龄" )))
					.addNode(new FieldNode("cplb_bxsxsj", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxsxsj", 30,0, false, "保险生效时间(小额信贷)" )))
					.addNode(new FieldNode("cplb_bxjssj", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxjssj", 30,0, false, "保险结束时间(小额信贷)" )))
					.addNode(new FieldNode("cplb_dkhtbh", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_dkhtbh", 15,0, false, "贷款合同编号(小额信贷)" )))
					.addNode(new FieldNode("cplb_dkje", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_dkje", 15,0, false, "贷款金额(小额信贷)" )))
					.addNode(new FieldNode("cplb_dkqsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_dkqsrq", 30,0, false, "贷款起始日期(小额信贷)" )))
					.addNode(new FieldNode("cplb_dkjsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_dkjsrq", 30,0, false, "贷款结束日期(小额信贷)" )))
					.addNode(new FieldNode("fjxsl", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxsl", 10,0, false, "附加险数量" )))
					.addNode(new ArrayNode("fjxlb",true,"fjxlb_list")
							.addNode(new FieldNode("fjxlb_fjxbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_fjxbz", 1,0, false, "附加险标志" )))
							.addNode(new FieldNode("fjxlb_cpdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_cpdm", 10,0, false, "附加险代码" )))
							.addNode(new FieldNode("fjxlb_tbfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_tbfs", 10,0, false, "附加险份数" )))
							.addNode(new FieldNode("fjxlb_qjbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_qjbf", 15,0, false, "附加险保费" )))
							.addNode(new FieldNode("fjxlb_bxje", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_bxje", 15,0, false, "附加险保额" )))
							.addNode(new FieldNode("fjxlb_bznq", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_bznq", 1,0, false, "附加险保障年期" )))
							.addNode(new FieldNode("fjxlb_jfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_jfnx", 10,0, false, "附加险缴费年期" )))
							.addNode(new FieldNode("fjxlb_jfnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_jfnqlx", 1,0, false, "附加险缴费年期类型" )))
							.addNode(new FieldNode("fjxlb_bznqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_bznqlx", 1,0, false, "附加险保障年期类型" )))
							.addNode(new FieldNode("fjxlb_jffs", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_jffs", 1,0, false, "附加险缴费方式" )))
							.addNode(new FieldNode("fjxlb_lqnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_lqnqlx", 1,0, false, "附加险领取方式" )))
							.addNode(new FieldNode("fjxlb_lqnl", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_lqnl", 10,0, false, "附加险领取年龄" )))
							.addNode(new FieldNode("fjxlb_hllqfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "fjxlb_hllqfs", 1,0, false, "附加险红利领取方式" )))
							).addNode(new FieldNode("qtxxjkgz", new MsgField(ContentEnum.MessageType.STRING.toString(), "qtxxjkgz", 1,0, false, "健康告知标志" )))
					.addNode(new FieldNode("qtxxcwgzbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "qtxxcwgzbz", 1,0, false, "财务告知标识" )))
					.addNode(new FieldNode("qtxxzygzbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "qtxxzygzbz", 1,0, false, "职业告知标识" )))
					.addNode(new FieldNode("jyxxjyzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxxjyzh", 30,0, false, "银行账户" )))
					.addNode(new FieldNode("jyxxjymm", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxxjymm", 20,0, false, "交易密码" )))
					.addNode(new FieldNode("bxxxcpdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxcpdm", 30,0, false, "产品代码" )))
					.addNode(new FieldNode("jyxxccs", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxxccs", 20,0, false, "车船税" )))
					.addNode(new FieldNode("yjylsh", new MsgField(ContentEnum.MessageType.STRING.toString(), "yjylsh", 30,0, false, "投保申请流水号" )))
					.addNode(new FieldNode("jyxxjyje", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxxjyje", 15,0, false, "收费金额" )))
					.addNode(new FieldNode("pzxxsjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "pzxxsjhm", 30,0, false, "发票号" )))
					.addNode(new FieldNode("OpenBranch", new MsgField(ContentEnum.MessageType.STRING.toString(), "OpenBranch", 20,0, true, "开卡机构" )))
					.addNode(new FieldNode("bankcode", new MsgField(ContentEnum.MessageType.STRING.toString(), "bankcode", 10,0, false, "银行代码" )))
					.addNode(new FieldNode("ptlsh", new MsgField(ContentEnum.MessageType.STRING.toString(), "ptlsh", 30,0, false, "交易流水号" )))
					.addNode(new FieldNode("zoneno", new MsgField(ContentEnum.MessageType.STRING.toString(), "zoneno", 8,0, false, "地区代码" )))
					.addNode(new FieldNode("pzxxtbdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "pzxxtbdh", 15,0, false, "投保单号" )))
					.addNode(new FieldNode("rbjgdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "rbjgdm", 10,0, false, "人保机构代码" )))
					.addNode(new FieldNode("jyxx_khlb", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxx_khlb", 3,0, false, "客户类别" )))
					.addNode(new FieldNode("jyxx_jyzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyxx_jyzh", 32,0, false, "交易帐号" )))
					.addNode(new FieldNode("pzxxbdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "pzxxbdh", 20,0, false, "保单号" )))
					.addNode(new FieldNode("dkxxdkhth", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkhth", 250,0, false, "贷款合同号" )))
					.addNode(new FieldNode("dkxxdkpzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkpzh", 250,0, false, "贷款凭证号" )))
					.addNode(new FieldNode("dkxxdkje", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkje", 6,0, false, "贷款金额" )))
					.addNode(new FieldNode("dkxxdkqq", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkqq", 8,0, false, "贷款起期" )))
					.addNode(new FieldNode("dkxxdkzq", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkzq", 8,0, false, "贷款止期" )))
					.addNode(new FieldNode("dkxxbxsxrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxbxsxrq", 8,0, false, "保险生效日期" )))
					.addNode(new FieldNode("dkxxbxhtzq", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxbxhtzq", 8,0, false, "保险合同止期" )))
					.addNode(new FieldNode("dkxxdkpz", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkpz", 1,0, false, "贷款品种" )))
					.addNode(new FieldNode("dkxxdkjg", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkjg", 20,0, false, "贷款机构" )))
					.addNode(new FieldNode("dkxxdklx", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdklx", 1,0, false, "贷款类型" )))
					.addNode(new FieldNode("dkxxdkzh", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkzh", 50,0, false, "贷款账号" )))
					.addNode(new FieldNode("dkxxdkyhmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkyhmc", 50,0, false, "贷款银行名称" )))
					.addNode(new FieldNode("dkxxdkyhlxdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "dkxxdkyhlxdh", 20,0, false, "贷款银行联系电话" )))
					.addNode(new FieldNode("fwxxfwdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "fwxxfwdz", 250,0, false, "投保房屋详细地址" )))
					.addNode(new FieldNode("qyxxqyxz", new MsgField(ContentEnum.MessageType.STRING.toString(), "qyxxqyxz", 10,0, false, "企业性质" )))
					.addNode(new FieldNode("qyxxyyxzdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "qyxxyyxzdm", 250,0, false, "营业性质代码" )))
					.addNode(new FieldNode("qyxxyyxzmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "qyxxyyxzmc", 2,0, false, "营业性质名称" )))
					.addNode(new FieldNode("qyxxbxjeqdfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "qyxxbxjeqdfs", 250,0, false, "保险金额确定方式" )))
					.addNode(new FieldNode("fwxxbqcqh", new MsgField(ContentEnum.MessageType.STRING.toString(), "fwxxbqcqh", 200,0, false, "保险标的产权证号" )))
					.addNode(new FieldNode("fwxxfwlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "fwxxfwlx", 2,0, false, "房屋类型" )))
					.addNode(new FieldNode("fwxxjzmj", new MsgField(ContentEnum.MessageType.STRING.toString(), "fwxxjzmj", 100,0, false, "建筑面积" )))
					.addNode(new FieldNode("bxxxdkxzdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxdkxzdm", 10,0, false, "贷款性质代码" )))
					.addNode(new FieldNode("bxxxdkyhdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxdkyhdm", 10,0, false, "贷款银行代码" )))
					.addNode(new FieldNode("bxxxbddx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbddx", 8,0, false, "标的大小" )))
					.addNode(new StructNode("bxxxbdjg",false)
							).addNode(new FieldNode("bxxxsfbhfsss", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxsfbhfsss", 2,0, false, "是否含室内附属设备" )))
					.addNode(new FieldNode("bxxxzwbl", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxzwbl", 2,0, false, "投保房屋性质" )))
					.addNode(new FieldNode("bxxxqfbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxqfbz", 10,0, false, "期房现房标志" )))
					.addNode(new FieldNode("bxxxqfjfrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxqfjfrq", 8,0, false, "交房日期" )))
					.addNode(new FieldNode("bxxxbddz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxbddz", 100,0, false, "标的地址" )))
					.addNode(new FieldNode("bxxxzyjjfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxzyjjfs", 20,0, false, "争议解决方式" )))
					.addNode(new FieldNode("bxxxtbfa", new MsgField(ContentEnum.MessageType.STRING.toString(), "bxxxtbfa", 20,0, false, "投保方案" )))
					);
			return messageNode;
		}
		@Override
		public ArrayList<Node> listNode() {
			return msgSegment.getNodeList();
		}

	}

	public static class BODF510104_O extends MsgBody {
		private MsgSegment  msgSegment = init();
		private MsgSegment init(){
			MsgSegment messageNode = new MsgSegment();
			messageNode
			.addStructNode(new StructNode("Body",true,"APPBody")
					.addNode(new FieldNode("jfrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "jfrq", 8,0, false, "缴费日期" )))
					.addNode(new FieldNode("cbgsmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "cbgsmc", 50,0, false, "承保公司名称" )))
					.addNode(new FieldNode("cbgsdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "cbgsdz", 50,0, false, "承保公司地址" )))
					.addNode(new FieldNode("cbgsdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "cbgsdh", 20,0, false, "承保公司电话" )))
					.addNode(new FieldNode("tbydbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbydbz", 1,0, false, "特别约定打印标志" )))
					.addNode(new FieldNode("tbrkhhscrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrkhhscrq", 8,0, false, "投保人客户号生成日期" )))
					.addNode(new FieldNode("bbrkhhscrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrkhhscrq", 8,0, false, "被保人客户号生成日期" )))
					.addNode(new FieldNode("resultcode", new MsgField(ContentEnum.MessageType.STRING.toString(), "resultcode", 10,0, false, "处理结果(返回码)" )))
					.addNode(new FieldNode("err_info", new MsgField(ContentEnum.MessageType.STRING.toString(), "err_info", 50,0, false, "错误原因" )))
					.addNode(new FieldNode("insure_serial", new MsgField(ContentEnum.MessageType.STRING.toString(), "insure_serial", 20,0, false, "交易流水号" )))
					.addNode(new FieldNode("tbdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbdh", 30,0, false, "投保单号" )))
					.addNode(new FieldNode("bdh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bdh", 30,0, false, "保单号(主险保险合同号)" )))
					.addNode(new FieldNode("tbrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrq", 8,0, false, "投保日期" )))
					.addNode(new FieldNode("sqbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "sqbf", 15,0, false, "首期保费" )))
					.addNode(new FieldNode("sqbfdx", new MsgField(ContentEnum.MessageType.STRING.toString(), "sqbfdx", 50,0, false, "首期保费大写" )))
					.addNode(new FieldNode("sxrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "sxrq", 8,0, false, "保单生效日期" )))
					.addNode(new FieldNode("tbrxm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrxm", 50,0, false, "投保人姓名" )))
					.addNode(new FieldNode("tbrkhh", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrkhh", 20,0, false, "投保人客户号" )))
					.addNode(new FieldNode("bbrxm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrxm", 50,0, false, "被保人姓名" )))
					.addNode(new FieldNode("bbrkhh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrkhh", 30,0, false, "被保人客户号" )))
					.addNode(new FieldNode("jffs", new MsgField(ContentEnum.MessageType.STRING.toString(), "jffs", 1,0, false, "缴费方式" )))
					.addNode(new FieldNode("jffshz", new MsgField(ContentEnum.MessageType.STRING.toString(), "jffshz", 50,0, false, "缴费方式汉字" )))
					.addNode(new FieldNode("cbgsdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "cbgsdm", 10,0, false, "承保公司代码" )))
					.addNode(new FieldNode("xqjfrqhzms", new MsgField(ContentEnum.MessageType.STRING.toString(), "xqjfrqhzms", 50,0, false, "续期缴费日期（汉字描述）" )))
					.addNode(new FieldNode("jfqzrqhzms", new MsgField(ContentEnum.MessageType.STRING.toString(), "jfqzrqhzms", 50,0, false, "缴费起止日期（汉字描述）" )))
					.addNode(new FieldNode("jfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "jfnx", 10,0, false, "缴费年期" )))
					.addNode(new FieldNode("xzgs", new MsgField(ContentEnum.MessageType.STRING.toString(), "xzgs", 3,0, false, "险种个数" )))
					.addNode(new StructNode("cplb",true)
							.addNode(new FieldNode("cplb_bxhth", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxhth", 30,0, false, "保险合同号" )))
							.addNode(new FieldNode("cplb_tbfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_tbfs", 10,0, false, "投保份数" )))
							.addNode(new FieldNode("cplb_zfxbz", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_zfxbz", 1,0, false, "主、附险标志" )))
							.addNode(new FieldNode("cplb_bxje", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxje", 15,0, false, "保额" )))
							.addNode(new FieldNode("cplb_qjbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_qjbf", 15,0, false, "保费" )))
							.addNode(new FieldNode("cplb_cpmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_cpmc", 50,0, false, "险种名称" )))
							.addNode(new FieldNode("cplb_bznqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bznqlx", 1,0, false, "保障年期类型" )))
							.addNode(new FieldNode("cplb_bxqmrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_bxqmrq", 50,0, false, "保险期满日期（汉字描述）" )))
							.addNode(new FieldNode("cplb_gznsbxqmrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_gznsbxqmrq", 8,0, false, "保险期满日期(广州农商行专用)" )))
							.addNode(new FieldNode("cplb_jfqmrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jfqmrq", 8,0, false, "缴费期满日期" )))
							.addNode(new FieldNode("cplb_jfnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jfnqlx", 1,0, false, "缴费年期类型" )))
							.addNode(new FieldNode("cplb_jfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplb_jfnx", 10,0, false, "缴费年期" )))
							).addNode(new FieldNode("dyxms", new MsgField(ContentEnum.MessageType.STRING.toString(), "dyxms", 10,0, false, "打印项目数" )))
					.addNode(new FieldNode("dydzgs", new MsgField(ContentEnum.MessageType.STRING.toString(), "dydzgs", 4,0, false, "打印单证个数" )))
					.addNode(new StructNode("detail_list",true)
							.addNode(new FieldNode("detail_list_dylx", new MsgField(ContentEnum.MessageType.STRING.toString(), "detail_list_dylx", 1,0, false, "打印类型" )))
							.addNode(new FieldNode("detail_list_dydzlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "detail_list_dydzlx", 2,0, false, "打印单证类型" )))
							.addNode(new FieldNode("detail_list_dyhs", new MsgField(ContentEnum.MessageType.STRING.toString(), "detail_list_dyhs", 10,0, false, "文件行数" )))
							.addNode(new StructNode("detail",true)
									.addNode(new FieldNode("detail_list_detail_dynr", new MsgField(ContentEnum.MessageType.STRING.toString(), "detail_list_detail_dynr", 255,0, false, "打印项" )))
									)).addNode(new FieldNode("jydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "jydm", 10,0, false, "保险公司端交易代码" )))
					.addNode(new FieldNode("yhdjydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "yhdjydm", 10,0, false, "银行端交易代码" )))
					.addNode(new FieldNode("ptlsh", new MsgField(ContentEnum.MessageType.STRING.toString(), "ptlsh", 30,0, false, "银行端的交易流水号" )))
					.addNode(new FieldNode("jyrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "jyrq", 10,0, false, "银行交易执行日期" )))
					.addNode(new FieldNode("jysj", new MsgField(ContentEnum.MessageType.STRING.toString(), "jysj", 10,0, false, "银行交易执行时间" )))
					.addNode(new FieldNode("dz", new MsgField(ContentEnum.MessageType.STRING.toString(), "dz", 30,0, false, "保险公司地址" )))
					.addNode(new FieldNode("yb", new MsgField(ContentEnum.MessageType.STRING.toString(), "yb", 10,0, false, "保险公司邮编" )))
					.addNode(new FieldNode("mc", new MsgField(ContentEnum.MessageType.STRING.toString(), "mc", 30,0, false, "保险公司名称" )))
					.addNode(new FieldNode("dhhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "dhhm", 20,0, false, "保险公司电话" )))
					.addNode(new FieldNode("khjlxm", new MsgField(ContentEnum.MessageType.STRING.toString(), "khjlxm", 10,0, false, "客户经理姓名" )))
					.addNode(new FieldNode("bdysh", new MsgField(ContentEnum.MessageType.STRING.toString(), "bdysh", 15,0, false, "保单印刷号" )))
					.addNode(new FieldNode("fpysh", new MsgField(ContentEnum.MessageType.STRING.toString(), "fpysh", 20,0, false, "发票印刷号" )))
					.addNode(new FieldNode("sqbfsz", new MsgField(ContentEnum.MessageType.STRING.toString(), "sqbfsz", 15,0, false, "首期保费(数值)" )))
					.addNode(new FieldNode("sqbfzw", new MsgField(ContentEnum.MessageType.STRING.toString(), "sqbfzw", 20,0, false, "首期保费(中文大写)" )))
					.addNode(new FieldNode("sqbfhj", new MsgField(ContentEnum.MessageType.STRING.toString(), "sqbfhj", 15,0, false, "首期保费合计" )))
					.addNode(new FieldNode("tbyd", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbyd", 30,0, false, "特别约定" )))
					.addNode(new FieldNode("tbrcsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrcsrq", 10,0, false, "投保人出生日期" )))
					.addNode(new FieldNode("tbrzjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjlx", 2,0, false, "投保人证件类型" )))
					.addNode(new FieldNode("tbrzjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzjhm", 20,0, false, "投保人证件号码" )))
					.addNode(new FieldNode("tbrzydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzydm", 10,0, false, "投保人职业代码" )))
					.addNode(new FieldNode("tbrzymc", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrzymc", 20,0, false, "投保人职业名称" )))
					.addNode(new FieldNode("tbrdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrdz", 30,0, false, "投保人地址" )))
					.addNode(new FieldNode("tbryb", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbryb", 10,0, false, "投保人邮编" )))
					.addNode(new FieldNode("tbrdhhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrdhhm", 20,0, false, "投保人电话" )))
					.addNode(new FieldNode("tbrsjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrsjhm", 11,0, false, "投保人手机" )))
					.addNode(new FieldNode("tbrybbrgxzw", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrybbrgxzw", 2,0, false, "与被保人关系(中文)" )))
					.addNode(new FieldNode("tbrybbrgx", new MsgField(ContentEnum.MessageType.STRING.toString(), "tbrybbrgx", 10,0, false, "与被保人关系(代码)" )))
					.addNode(new FieldNode("bbrmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrmc", 20,0, false, "被保人姓名" )))
					.addNode(new FieldNode("bbrxb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrxb", 2,0, false, "被保人性别" )))
					.addNode(new FieldNode("bbrcsrq", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrcsrq", 10,0, false, "被保人出生日期" )))
					.addNode(new FieldNode("bbrzjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjlx", 2,0, false, "被保人证件类型" )))
					.addNode(new FieldNode("bbrzjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzjhm", 20,0, false, "被保人证件号码" )))
					.addNode(new FieldNode("bbrzydm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzydm", 10,0, false, "被保人职业代码" )))
					.addNode(new FieldNode("bbrzymc", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrzymc", 20,0, false, "被保人职业名称" )))
					.addNode(new FieldNode("bbrdz", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdz", 30,0, false, "被保人地址" )))
					.addNode(new FieldNode("bbryb", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbryb", 10,0, false, "被保人邮编" )))
					.addNode(new FieldNode("bbrdhhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrdhhm", 20,0, false, "被保人电话" )))
					.addNode(new FieldNode("bbrsjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "bbrsjhm", 11,0, false, "被保人手机" )))
					.addNode(new FieldNode("syrsl", new MsgField(ContentEnum.MessageType.STRING.toString(), "syrsl", 10,0, false, "受益人数量" )))
					.addNode(new StructNode("syr",true)
							.addNode(new FieldNode("syr_xm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_xm", 20,0, false, "受益人姓名" )))
							.addNode(new FieldNode("syr_xb", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_xb", 2,0, false, "受益人性别" )))
							.addNode(new FieldNode("syr_zjlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_zjlx", 2,0, false, "受益人证件类型" )))
							.addNode(new FieldNode("syr_zjhm", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_zjhm", 20,0, false, "受益人证件号码" )))
							.addNode(new FieldNode("syr_sysx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_sysx", 2,0, false, "受益顺序" )))
							.addNode(new FieldNode("syr_sybl", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_sybl", 5,0, false, "受益份额" )))
							.addNode(new FieldNode("syr_ybbrgx", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_ybbrgx", 2,0, false, "受益人与被保人关系(代码)" )))
							.addNode(new FieldNode("syr_ybbrgxzw", new MsgField(ContentEnum.MessageType.STRING.toString(), "syr_ybbrgxzw", 10,0, false, "受益人与被保人关系(中文)" )))
							).addNode(new FieldNode("cplbcpdm", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbcpdm", 10,0, false, "险种代码" )))
					.addNode(new FieldNode("cplbcpmc", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbcpmc", 20,0, false, "险种名称" )))
					.addNode(new FieldNode("cplbhllqfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbhllqfs", 2,0, false, "红利领取方式(中文)" )))
					.addNode(new FieldNode("cplbtbfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbtbfs", 10,0, false, "险种份数" )))
					.addNode(new FieldNode("cplbjfnqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbjfnqlx", 2,0, false, "缴费年期类型(中文)" )))
					.addNode(new FieldNode("cplbjfnx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbjfnx", 10,0, false, "缴费年期" )))
					.addNode(new FieldNode("cplbbznqlx", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbbznqlx", 2,0, false, "保障年期类型(中文)" )))
					.addNode(new FieldNode("cplbbznq", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbbznq", 10,0, false, "保障年期" )))
					.addNode(new FieldNode("cplbbxje", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbbxje", 15,0, false, "保额" )))
					.addNode(new FieldNode("cplbzxbf", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbzxbf", 15,0, false, "保费" )))
					.addNode(new FieldNode("cplbbxqmr", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbbxqmr", 20,0, false, "保险期满日" )))
					.addNode(new FieldNode("cplbjfqmr", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbjfqmr", 20,0, false, "缴费期满日" )))
					.addNode(new FieldNode("cplbcsfybl", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbcsfybl", 10,0, false, "初始费用比例" )))
					.addNode(new FieldNode("cplbnjlqfs", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbnjlqfs", 2,0, false, "年金领取方式(中文)" )))
					.addNode(new FieldNode("cplbsqglfje", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbsqglfje", 15,0, false, "首期管理费金额" )))
					.addNode(new FieldNode("cplbmpe", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbmpe", 15,0, false, "免赔额" )))
					.addNode(new FieldNode("cplbpfbl", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbpfbl", 10,0, false, "赔付比例" )))
					.addNode(new FieldNode("cplbnjkslqr", new MsgField(ContentEnum.MessageType.STRING.toString(), "cplbnjkslqr", 20,0, false, "年金开始领取日(中文)" )))
					.addNode(new FieldNode("xjjznf", new MsgField(ContentEnum.MessageType.STRING.toString(), "xjjznf", 10,0, false, "现金价值表年份" )))
					.addNode(new FieldNode("xjjzscnj", new MsgField(ContentEnum.MessageType.STRING.toString(), "xjjzscnj", 15,0, false, "现金价值表生存年金" )))
					.addNode(new FieldNode("xjjzjbsgbxj", new MsgField(ContentEnum.MessageType.STRING.toString(), "xjjzjbsgbxj", 15,0, false, "疾病身故保险金" )))
					.addNode(new FieldNode("xjjzywsgbxj", new MsgField(ContentEnum.MessageType.STRING.toString(), "xjjzywsgbxj", 15,0, false, "意外身故保险金" )))
					.addNode(new FieldNode("xjjznmxjjz", new MsgField(ContentEnum.MessageType.STRING.toString(), "xjjznmxjjz", 15,0, false, "年末现金价值" )))
					);
			return messageNode;
		}
		@Override
		public ArrayList<Node> listNode() {
			return msgSegment.getNodeList();
		}
	}
}

